### ISSUE TITLE
インストール可能なアプリケーション一覧画面が欲しい

### ISSUE THREAD

**Issue by yzkjs327** [Wabyon/Candy#12]
サーバ上の applications.json から簡単な一覧形式でインストール可能なアプリケーション一覧画面を起動できるようにしたい。
さらに言うとそこから選択してインストール出来るようにしたい。

**Comment by pianikuro** [comment]
#8 と一緒に出来そうな感じ

**Comment by pianikuro** [comment]
#8 と一緒に出来そうとか言っといて、全くそっち側のイメージがつかめてない・・・

**Comment by pianikuro** [comment]
ついでに登録・インストールのブロックを固定領域に持っていきたい
(別issueの方がいいのかな)

**Comment by chocolamint** [comment]
> 別issueの方がいい

ですね

**Comment by pianikuro** [comment]
もう #14 に作ってたでした

**Comment by yuki87** [comment]
本Issueですが、
「アプリケーションをインストール」を選択→アプリ一覧表示→選択でインストール
という実装をしようと思います。

**Comment by chocolamint** [comment]
:+1:

**Comment by ksuke** [comment]
#31 にて解決済みのためクローズとします
