### ISSUE TITLE
メイン画面下部のインストールボタンは、下に固定するべきか否か

### ISSUE THREAD

**Issue by pianikuro** [Wabyon/Candy#14]
スクロールを出したことにより、スクロールを下に行けば増えても見られるようになったが、
そもそも下に固定しておいたほうがよいのではないか(下部の謎空間)。

**Comment by chocolamint** [comment]
そういえばだいぶ前に口頭かSlackかで話しましたが

> (下部の謎空間)

はただの不具合です。アプリバー的なものを置こうとして実験してたやつが間違ってコミット（当時はチェックイン？）されてたっぽい。

**Comment by ksuke** [comment]
下部の謎空間に固定するように修正しました
